parameters:
  mailer.gmail_user: 'lior@gmail.com'
  mailer.gmail_password: '123456'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $firstName: "Julien"

  App\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection}"

  App\Controller\OrderController:
    public: true

  App\Controller\TestController:
    public: true

  App\Mailer\MailerInterface:
    alias: App\Mailer\GmailMailer

  App\Texter\TexterInterface:
    alias: App\Texter\SmsTexter

  App\Mailer\GmailMailer:
    arguments:
      - "%mailer.gmail_user%"
      - "%mailer.gmail_password%"

  App\Texter\SmsTexter:
    arguments:
      - "service.sms.com"
      - "apikey1234"

  order_controller:
    alias: App\Controller\OrderController
    public: true
